- name: Provision FTF GeoNode into Production
  hosts: production
  remote_user: ubuntu
  vars:
    app_name: ftf_geonode
    github_user: ftf-geonode
    server_name: 0.0.0.0
    deploy_user: ubuntu
    code_repository: "https://github.com/ftf-geonode/ftf_geonode.git"
    branch_name: master
    virtualenv_dir: "/home/ubuntu/.venvs"
    site_url: "http://localhost:8000/"
    geoserver_url: "http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war"
  roles:
     - { role: GeoNode.geonode }
